version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      -echo Build compeleted successfully
artifacts:
  files:
    -target/user-management-service.jar
  discard-paths: yes